FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential curl

COPY requirements.txt requirements-train.txt ./
RUN pip install -r requirements-train.txt -r requirements.txt

COPY app/ ./
RUN python generate_dataset.py && python train.py

ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
